links:
  - label: Book Now
    color: primary
    size: md
    variant: link
description: Face painting at your event provides fun filled activities both children and adults can enjoy. Make people feel special by offering creative bespoke designs. Pricing options are 2+ hrs to paint up to 30 people, or pay per face options.
title: From corporate family days to community fairs, we create joyful memories that last long after the paint fades
