links:
  - label: Book Now
    color: primary
    size: md
    variant: link
description: 'Face painting is fun, enjoyed by children and adlts. Make people feel special with our creative bespoke designs. Pricing options range from 2+ hrs to paint up to 30 people. '
title: Creating joyful memories that last long after the paint fades
